baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Echo'
theme = 'archie'
enableEmoji = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Echo to the world. Contribute [here](https://github.com/dheimgartner)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[menu.main]]
name = "README"
url = "/readme"
weight = 1